# -*- coding: utf-8 -*-
"""Super Resolution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTeewPouz1AHoyhIv3rq8kIZ3X6mDKww
"""

import cv2
from cv2 import dnn_superres

sr = dnn_superres.DnnSuperResImpl_create()
#path = 'EDSR_x4.pb'
path = 'LapSRN_x8.pb'
sr.readModel(path)
#sr.setModel('edsr', 4)
sr.setModel('lapsrn', 8)

image = cv2.imread('warrior.jpg')
result = sr.upsample(image)
cv2.imwrite('warrior_upscaled_8x.jpg', result)